# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 16 * * *'
    - cron: '0 18 * * *'
    - cron: '0 20 * * *'
    - cron: '0 22 * * *'
    - cron: '0 0 * * *'  
    - cron: '0 5 * * *'

jobs:
  run-csjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master  #采用main分支下的
           
      - name: Setup Node.js
        uses: actions/setup-node@v2  #安装node.js
        with:
          node-version: '14'
          
      - name: Run       
        run: |
          npm install         
          npm run start
        env: 
          OPEN_ID: ${{ secrets.OPEN_ID }}